### PR TITLE
Add poetry project definition

### PR DESCRIPTION
**Pull request by alexpovel**
Hi,

I'm going to attend this coming Tuesday and had gone through the content in preparation. I have never used Anaconda and didn't want to install it for fear of it messing up my existing setup. For project dependency management and virtual environments, I use [`poetry`](https://python-poetry.org/). It works really well. As such, I took your config file:

https://github.com/1kastner/einfuehrung-in-jupyter-notebooks/blob/44fca25843b32e840a30c8f9355c6bfad1c58225/environment.yml

and basically implemented its equivalent poetry config file. One can then, after installing `poetry` itself, run `poetry install` to install the according virtual environment, then `poetry run jupyter-lab` to start `jupyter-lab` within that venv. So far, it works, and all notebooks currently contained in the repo run successfully. I'm on Python 3.9 and that also works fine. Including `pyproject.toml` could help other `poetry` users (probably no one..) to get started quickly.

### CODE REVIEW

**Comment by 1kastner** [comment]
Why do you believe that Anaconda would mess up your system? Do you have previous bad experience with it?

Why do you believe that poetry solves the task of dependency management and environment isolation better than conda?

**Comment by alexpovel** [comment]
Python dependency management is a gigantic pain in the behind. I guess we can agree on that...

Anaconda seems (correct me if I'm wrong--I'm aware they distribute to Linux and macOS too) to be a very Windows- and Data Science-centric approach. It's just a narrow tool in the grand scheme of things. From what I understand it's excellent at what it does (install data science Python environments on Windows), so it's the correct choice for this project!

Poetry is turning out to be the current de-facto go-to standard for general purpose Python project management. This of course includes the entire data science stack, but, most importantly, it's not limited to it. It also works equally well on all platforms. It implements `pyproject.toml` aka [PEP 518](https://www.python.org/dev/peps/pep-0518/) and is therefore adhering to Python-wide, agreed upon standards. That's always welcome! `environment.yml` seems to be Anaconda-specific. Poetry also handles the entire package building and publishing to the cheese shop chain, which I've never used though. It also works really well for [CI pipelines](https://collaborating.tuhh.de/alex/latex-git-cookbook/-/blob/7bca167b86d7afabf2ad7b7307c80ac78a534f80/.gitlab-ci.yml#L66-70) (seems to be [true for `conda` as well though](https://github.com/ContinuumIO/docker-images)).

Installing Anaconda, it seems I either have to add it to `$PATH`  (this is the "messing up" part, I want to retain my existing Python 3.9) or use the Anaconda prompt. Using a foreign terminal/prompt is a non-starter, I am relying heavily on Windows Terminal and am quite happy with it. The base Anaconda terminal seems to be `cmd`-based, took me a while to find out you have to launch a dedicated Anaconda PowerShell terminal.

Again--if you don't have Python installed yet at all, then Anaconda is fine. Therefore, it's the correct choice for this project. It just doesn't integrate well with an existing Python installation. And I'm cranky because I don't want to learn anything new and keep using my existing tools :^)

The PR just adds a simple and easy way for `poetry` to be used, for anyone who'd like to, without hurting the Anaconda setup. It adds a maintenance burden for you since any changes to the Python environment would now have to be reflected in *both* `environment.yml` and poetry (`poetry add <package>`. So for you, it's more work for no benefit as it stands right now (`poetry` is still worth a look regardless, I recommend it).

**Comment by 1kastner** [comment]
Well, I guess then you already have downloaded and installed many dev-related tools and libraries on your machine. For most workshop participants, compiling all required libraries themselves would be too much to reasonably ask for for a simple 3-hour learning unit.

I have a suggestion: You could set up a gist and I can link it in the readme file. That way people who are willing to use poetry in the future have an easier start to setup their own file.

**Comment by alexpovel** [comment]
> For most workshop participants, compiling all required libraries themselves would be too much to reasonably ask for for a simple 3-hour learning unit.

Yeah, definitely. These days I just do `poetry install` and it "just works", but there's probably dependencies like a C compiler that I installed a while ago and forgot about (but which is required for `pandas` IIRC). Docker would be the tool of choice then, but that's a different chapter altogether.

> I have a suggestion: You could set up a gist and I can link it in the readme file. That way people who are willing to use poetry in the future have an easier start to setup their own file.

Feel free to copy-paste the above `pyproject.toml` into a gist, that way you could keep it updated.

**Comment by 1kastner** [comment]
Thank you very much for setting up the file and reason with me about what is suitable for a workshop. It is always great to learn more!

**Comment by 1kastner** [comment]
@alexpovel would you mind reviewing https://gist.github.com/1kastner/032ea28683e6cbbf9f05391efa0187fa ?

I guess the distinction betweek `[tool.poetry.dependencies]` and `[tool.poetry.dev-dependencies]` are rather cosmetic at this point? As you moved down the packages that improve the development experience, I also moved the language server down.

**Comment by alexpovel** [comment]
The gist looks good to me.

Under normal circumstances, the differences between `[tool.poetry.dependencies]` and `[tool.poetry.dev-dependencies]` are pretty substantial: the former is for users to run the project, the latter to develop in it. Since we're users most of the time, it's nice to not care for the dev dependencies. But with notebooks, as you said, it's mostly reduced to a cosmetic difference, yeah. You don't really "use" notebooks without also "developing" in them.

Perhaps this makes sense:

- for strictly read-only, viewing (running cells without interacting further), `[tool.poetry.dependencies]` is required
- if editing is also desired, `[tool.poetry.dev-dependencies]` come into play

**Comment by 1kastner** [comment]
A remark has been added to the README with https://github.com/1kastner/einfuehrung-in-jupyter-notebooks/commit/86d2aa285bfc8d59397066e4b815360648f2fedb

**Pull request closed without merging**
