### PR TITLE
A couple minor improvements

### PR DESCRIPTION
**Pull request by alexpovel**
A couple clarifications and improvements here and there, see if you agree.

### CODE REVIEW

**Comment by 1kastner** [comment]
I agree to all except the first part of commit ad3f778baeb5a07631f12617f493212555583880 - and this depends on how I work with that Notebook. I love to quickly copy and paste library names into the multi line string without worrying about syntax.

**Comment by alexpovel** [comment]
OK, done.

**Comment by 1kastner** [comment]
Thank you very much! The introduction is much better now.

**Comment by alexpovel** [comment]
Well perhaps a tiny bit! See you tomorrow, thanks for merging this.

**Comment by 1kastner** [comment]
Some small fixes and extensions:
- https://github.com/1kastner/einfuehrung-in-jupyter-notebooks/commit/e0d8b2107b2b4a430b9a53db6c4776f893629e05 
- https://github.com/1kastner/einfuehrung-in-jupyter-notebooks/commit/d361b087e2174a610d012df8b106de8bc9be3308

**Comment by 1kastner** [comment]
@alexpovel see you later.

**Pull request merged**
